# Generated by Django 2.2.10 on 2020-12-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1200, max_digits=10),
            preserve_default=False,
        ),
    ]
